services:
  - type: web
    name: api-tareas-express
    runtime: node
    plan: free
    buildCommand: npm ci --omit=dev
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_SSL
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: api-tareas-db
          property: connectionString

databases:
  - name: api-tareas-db
    plan: free
    databaseName: tareas
    user: tareas_api
