services:
  - type: web
    name: api-tareas-express
    runtime: node
    plan: free
    buildCommand: npm ci --omit=dev
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_SSL
        value: true
      - key: DATABASE_URL
        sync: false
